version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    allow: 
      - dependency-name: "greentic-*"
      - dependency-name: "qa-spec"
