version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    allow:
      - dependency-name: "greentic-*"
      - dependency-name: "qa-spec"
    groups:
      greentic-interfaces-stack:
        patterns:
          - "greentic-interfaces"
          - "greentic-interfaces-host"
          - "greentic-interfaces-wasmtime"
