[patch.crates-io]
# Internal crates to be patched from AWS CodeArtifact in dev/develop
greentic-types = { version = "__GREENTIC_TYPES_DEV_VERSION__", registry = "corp-artifacts-greentic" }
# greentic-interfaces-host = { registry = "corp-artifacts-greentic" }
# greentic-interfaces-wasmtime = { registry = "corp-artifacts-greentic" }
# greentic-distributor-client = { registry = "corp-artifacts-greentic" }
# greentic-qa-lib = { registry = "corp-artifacts-greentic" }
# greentic-i18n-translator = { registry = "corp-artifacts-greentic" }
# qa-spec = { registry = "corp-artifacts-greentic" }
